#!/bin/bash

echo "🚀 Setting up Friends System for Syrena Travel"
echo "=============================================="
echo ""
echo "This script will create the necessary database tables for the friends system."
echo ""
echo "Please run the SQL migration in your Supabase project:"
echo ""
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy and paste the contents of: supabase/migrations/002_add_friendships.sql"
echo "4. Click 'Run' to execute the migration"
echo ""
echo "The migration will:"
echo "✅ Create profiles table for usernames"
echo "✅ Create friendships table for friend connections"
echo "✅ Update RLS policies to only show friends' places"
echo "✅ Add triggers to auto-create profiles on signup"
echo ""
echo "After running the migration, update your app to use FriendsNew component:"
echo ""
echo "In src/app/page.tsx, replace:"
echo "  import Friends from '@/components/Friends';"
echo "With:"
echo "  import Friends from '@/components/FriendsNew';"
echo ""
echo "=============================================="